#!/usr/bin/env bash

if [[ "$PWD" = *scripts* ]]
then 
    echo 'this directory name contains the string scripts'
else 
    echo 'this directory name does not contain the string scripts'
fi

echo 'the end'  

