#!/bin/bash

# Browse the trac URL of the current branch of a suite working copy.
SVN_URL=$(fcm info | egrep '^URL:' | sed -e 's/URL: //')
TMP_URL=${SVN_URL/svn/trac}
TRAC_URL=${TMP_URL/roses-u/roses-u\/log}
firefox $TRAC_URL &
