#!/bin/bash
########################################################
#                                                      #
# This is a simple script to display the complete      #
# list of suite revsions in a MOSRS Rose/Cylc          #
# suite in a Firefox web browser.                      # 
#                                                      # 
# Date of first revision: 8/1/16                       # 
#                                                      #
# Author: Jonny Williams                               #
#                                                      #
# Organisation:                                        # 
#    __  _   __ _   _   __  __                         #
#   /  |/ / / /| | / | / / /  |  National Institute of #
#  /  |  / / / | |/ /|/ / / / |  Water and Atmospheric #
# /__/|_/ /_/  |_/_/ |_/ /_/|_|  Research Ltd          # 
#                                                      #
######################################################## 

URL=https://code.metoffice.gov.uk/trac/roses-u/log

for i in 5 4 3 2 1

do

URL=$URL/${PWD: -$i:1}

done

URL=$URL/trunk

firefox $URL &
