#!/usr/bin/env bash
# this is a script to see where a run has got to...

export suiteid=$1

clear

grep -r 'Atm_Step: Timestep' ~/cylc-run/$suiteid/work/*/*/pe_output/*|tail -1
echo '---------------------------'

