#!/bin/bash

# UM

basedir=/group_workspaces/jasmin2/tids

outfile=TIDS_files_to_retrieve

echo \#\#\#\#\# > /$outfile

for i in $(seq 1 3)

    do 

    if [ $i -eq 1 ]; then

        dir=$basedir/UM/ancil/atmos/n96e

        echo $i 
        echo $dir

    fi

    if [ $i -eq 2 ]; then

        dir=$basedir/UM/ancil/atmos/n216e

        echo $i 
        echo $dir

    fi


    if [ $i -eq 3 ]; then

        dir=$basedir/OCEAN

        echo $i 
        echo $dir

    fi

    echo \#\#\#\#\#>> $outfile
    echo \#$dir >> $outfile
    echo \#\#\#\#\#>> $outfile

    find $dir -name "[!.]*" -type f >> $outfile 

    paste $outfile $outfile > 2_column_$outfile
    rm $outfile

done

