#!/bin/bash

# UM

tids=/group_workspaces/jasmin2/tids

cd $tids
echo 'I am now in the top level directory where all of the retrievals will occur from, this is' $PWD
echo ''

outfile=TIDS_files_to_retrieve

echo \#\#\#\#\# > $outfile


#these variables can be defined in (for example) your ~/.bashrc file

echo 'I am now loading the globus directories which I want to retrieve. I have defined these in my ~/.bashrc'
echo ''
. ~/.bashrc

dir[1]=$globus_dir_001
dir[2]=$globus_dir_002
dir[3]=$globus_dir_003
dir[4]=$globus_dir_004

echo 'This is the array of directories which will be retrieved...'
echo ${dir[*]}
echo ''

for i in {1..4}

    do 

    echo 'Now retrieving list from' ${dir[$i]}
    echo ''

    echo \#\#\#\#\#>> $outfile
    echo \#${dir[$i]} >> $outfile
    echo \#\#\#\#\#>> $outfile

    find ${dir[$i]} -name "[!.]*" -type f >> $outfile 

    paste $outfile $outfile > 2_column_$outfile

done

mv /group_workspaces/jasmin2/tids/2_column_$outfile ~/scripts/
rm $tids/$outfile
cd ~/scripts

echo 'You can now retrieve the files you want using this command [insert command here!]' 

echo ''

echo 'Done. Exiting and returning to your ~/scripts directory.'
